# Dependencies
markdown:         kramdown
highlighter:      Rouge
plugins:          [jekyll-paginate, jekyll-sitemap, jekyll-gist, jekyll-feed, jekyll-include-cache]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            CISL@UCR
#tagline:          'A Jekyll theme'
#description:      Collaborative Intelligence Systems Lab
url:              https://UCR-CISL.github.io/
baseurl:

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

## Custom vars
#version:          2.1.0
#
#github:
#  repo:           https://github.com/poole/hyde
